// <auto-generated />
using System;
using HiWallet.Bank.Fake.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiWallet.Bank.Fake.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BankFakeDbContext))]
    partial class BankFakeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiWallet.Bank.Fake.Infrastructure.Persistence.BankTransfer", b =>
                {
                    b.Property<string>("BankReference")
                        .HasColumnType("text")
                        .HasColumnName("bank_reference");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<int>("CallbackAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("callback_attempts");

                    b.Property<DateTimeOffset?>("CallbackSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("callback_sent_at");

                    b.Property<string>("ClientReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_reference");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DestinationIban")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_iban");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fee");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastCallbackError")
                        .HasColumnType("text")
                        .HasColumnName("last_callback_error");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset>("ResolveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolve_at");

                    b.HasKey("BankReference")
                        .HasName("pk_transfers");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_transfers_idempotency");

                    b.HasIndex("ResolveAt")
                        .HasDatabaseName("ix_transfers_pending_callback")
                        .HasFilter("callback_sent_at IS NULL");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("HiWallet.Bank.Fake.Infrastructure.Persistence.TransferScenario", b =>
                {
                    b.Property<string>("ClientReference")
                        .HasColumnType("text")
                        .HasColumnName("client_reference");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DelayMilliseconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("delay_milliseconds");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int>("RemainingTransientFailures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("remaining_transient_failures");

                    b.HasKey("ClientReference")
                        .HasName("pk_transfer_scenarios");

                    b.ToTable("transfer_scenarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
