// <auto-generated />
using System;
using HiWallet.StaffAdmin.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiWallet.StaffAdmin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StaffAdminDbContext))]
    [Migration("20261002125015_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiWallet.StaffAdmin.Domain.StaffAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorName")
                        .HasColumnType("text")
                        .HasColumnName("actor_name");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_subject");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_label");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_staff_audit_events");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_staff_audit_events_target_id");

                    b.ToTable("staff_audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_staff_audit_events_action", "action IN ('role_created','role_updated','role_deleted','staff_invited','staff_roles_changed','staff_disabled','staff_enabled','invitation_sent')");

                            t.HasCheckConstraint("ck_staff_audit_events_target_type", "target_type IN ('role','staff')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
