// <auto-generated />
using System;
using System.Collections.Generic;
using HiWallet.StaffAdmin.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiWallet.StaffAdmin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StaffAdminDbContext))]
    [Migration("20261003003521_StaffDirectory")]
    partial class StaffDirectory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiWallet.StaffAdmin.Domain.StaffAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorName")
                        .HasColumnType("text")
                        .HasColumnName("actor_name");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_subject");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_label");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_staff_audit_events");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_staff_audit_events_target_id");

                    b.ToTable("staff_audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_staff_audit_events_action", "action IN ('role_created','role_updated','role_deleted','staff_invited','staff_roles_changed','staff_disabled','staff_enabled','invitation_sent')");

                            t.HasCheckConstraint("ck_staff_audit_events_target_type", "target_type IN ('role','staff')");
                        });
                });

            modelBuilder.Entity("HiWallet.StaffAdmin.Domain.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_staff_members");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_members_email");

                    b.ToTable("staff_members", (string)null);
                });

            modelBuilder.Entity("HiWallet.StaffAdmin.Domain.StaffRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.HasKey("Id")
                        .HasName("pk_staff_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_roles_normalized_name");

                    b.ToTable("staff_roles", (string)null);
                });

            modelBuilder.Entity("HiWallet.StaffAdmin.Domain.StaffRoleAssignment", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("StaffId", "RoleId")
                        .HasName("pk_staff_role_assignments");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_staff_role_assignments_role_id");

                    b.ToTable("staff_role_assignments", (string)null);
                });

            modelBuilder.Entity("HiWallet.StaffAdmin.Domain.StaffRoleAssignment", b =>
                {
                    b.HasOne("HiWallet.StaffAdmin.Domain.StaffRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staff_role_assignments_staff_roles");

                    b.HasOne("HiWallet.StaffAdmin.Domain.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_staff_role_assignments_staff_members");
                });
#pragma warning restore 612, 618
        }
    }
}
