<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.OpenTelemetry"/>

        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="Swashbuckle.AspNetCore"/>

        <PackageReference Include="WolverineFx"/>

        <PackageReference Include="OpenTelemetry.Extensions.Hosting"/>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Http"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime"/>
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql"/>
    </ItemGroup>

    <!-- Integration testler WebApplicationFactory ile Program'a erişir. -->
    <ItemGroup>
        <InternalsVisibleTo Include="HiWallet.WalletService.IntegrationTests"/>
    </ItemGroup>

</Project>
