// <auto-generated />
using System;
using HiWallet.BankIntegration.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiWallet.BankIntegration.Persistence.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260915104005_InitialBankIntegration")]
    partial class InitialBankIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiWallet.BankIntegration.Persistence.BankCallback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("ProcessAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("process_attempts");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Id")
                        .HasName("pk_bank_callbacks");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_bank_callbacks_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.HasIndex("Provider", "EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_bank_callbacks_event");

                    b.ToTable("bank_callbacks", (string)null);
                });

            modelBuilder.Entity("HiWallet.BankIntegration.Persistence.BankTransfer", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("BankReference")
                        .HasColumnType("text")
                        .HasColumnName("bank_reference");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DestinationIban")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_iban");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fee");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("PublishAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("publish_attempts");

                    b.Property<string>("ReplyPayload")
                        .HasColumnType("text")
                        .HasColumnName("reply_payload");

                    b.Property<DateTimeOffset?>("ReplyPublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reply_published_at");

                    b.Property<string>("ReplyRoutingKey")
                        .HasColumnType("text")
                        .HasColumnName("reply_routing_key");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedVia")
                        .HasColumnType("text")
                        .HasColumnName("resolved_via");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("CommandId")
                        .HasName("pk_bank_transfers");

                    b.HasIndex("BankReference")
                        .HasDatabaseName("ix_bank_transfers_reference")
                        .HasFilter("bank_reference IS NOT NULL");

                    b.HasIndex("ResolvedAt")
                        .HasDatabaseName("ix_bank_transfers_unpublished")
                        .HasFilter("resolved_at IS NOT NULL AND reply_published_at IS NULL");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_bank_transfers_pending")
                        .HasFilter("resolved_at IS NULL");

                    b.ToTable("bank_transfers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
