// <auto-generated />
using System;
using HiWallet.Onboarding.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiWallet.Onboarding.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OnboardingDbContext))]
    partial class OnboardingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiWallet.Onboarding.Domain.Consent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_consents");

                    b.HasIndex("Subject", "Document", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_consents_subject_document_version");

                    b.ToTable("consents", null, t =>
                        {
                            t.HasCheckConstraint("ck_consents_document", "document IN ('terms','privacy_notice')");
                        });
                });

            modelBuilder.Entity("HiWallet.Onboarding.Domain.Customer", b =>
                {
                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset?>("BasicVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("basic_verified_at");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<DateTimeOffset?>("IdentityVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("identity_verified_at");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("NationalId")
                        .HasColumnType("char(11)")
                        .HasColumnName("national_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_verified_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Subject")
                        .HasName("pk_customers");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_national_id")
                        .HasFilter("national_id IS NOT NULL");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_customers_phone")
                        .HasFilter("phone IS NOT NULL");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("HiWallet.Onboarding.Domain.PhoneChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("NewPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_phone");

                    b.Property<string>("OldPhone")
                        .HasColumnType("text")
                        .HasColumnName("old_phone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_phone_changes");

                    b.HasIndex("Subject")
                        .HasDatabaseName("ix_phone_changes_subject");

                    b.ToTable("phone_changes", (string)null);
                });

            modelBuilder.Entity("HiWallet.Onboarding.Domain.PhoneVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("basic")
                        .HasColumnName("purpose");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_phone_verifications");

                    b.HasIndex("Subject")
                        .HasDatabaseName("ix_phone_verifications_subject");

                    b.ToTable("phone_verifications", (string)null);
                });

            modelBuilder.Entity("HiWallet.Onboarding.Domain.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("code_expires_at");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_registrations");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_registrations_account_id")
                        .HasFilter("account_id IS NOT NULL");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_registrations_email");

                    b.HasIndex("Subject")
                        .HasDatabaseName("ix_registrations_subject");

                    b.ToTable("registrations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
