// <auto-generated />
using System;
using HiWallet.WalletService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiWallet.WalletService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WalletDbContext))]
    [Migration("20260911121018_RequireIdempotencyKey")]
    partial class RequireIdempotencyKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiWallet.WalletService.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_type", "type IN ('person','business')");
                        });
                });

            modelBuilder.Entity("HiWallet.WalletService.Domain.Balances.LedgerBalance", b =>
                {
                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(19,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("LedgerAccountId")
                        .HasName("pk_ledger_balances");

                    b.HasIndex("LedgerAccountId", "Currency")
                        .HasDatabaseName("ix_ledger_balances_ledger_account_currency");

                    b.ToTable("ledger_balances", (string)null);

                    b.HasData(
                        new
                        {
                            LedgerAccountId = new Guid("a0000000-0000-4000-8000-000000000001"),
                            Balance = 0m,
                            Currency = "TRY",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 0L
                        },
                        new
                        {
                            LedgerAccountId = new Guid("a0000000-0000-4000-8000-000000000002"),
                            Balance = 0m,
                            Currency = "TRY",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 0L
                        },
                        new
                        {
                            LedgerAccountId = new Guid("a0000000-0000-4000-8000-000000000003"),
                            Balance = 0m,
                            Currency = "TRY",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 0L
                        },
                        new
                        {
                            LedgerAccountId = new Guid("a0000000-0000-4000-8000-000000000004"),
                            Balance = 0m,
                            Currency = "TRY",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 0L
                        },
                        new
                        {
                            LedgerAccountId = new Guid("a0000000-0000-4000-8000-000000000005"),
                            Balance = 0m,
                            Currency = "TRY",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 0L
                        },
                        new
                        {
                            LedgerAccountId = new Guid("a0000000-0000-4000-8000-000000000006"),
                            Balance = 0m,
                            Currency = "TRY",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 0L
                        });
                });

            modelBuilder.Entity("HiWallet.WalletService.Domain.Ledger.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderKey")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("provider_key")
                        .HasComputedColumnSql("COALESCE(provider, '')", true);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ledger_accounts");

                    b.HasAlternateKey("Id", "Currency")
                        .HasName("uq_ledger_accounts_id_currency");

                    b.HasIndex("Type", "ProviderKey", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_accounts_system")
                        .HasFilter("account_id IS NULL");

                    b.HasIndex(new[] { "AccountId" }, "ix_ledger_accounts_account")
                        .HasFilter("account_id IS NOT NULL");

                    b.ToTable("ledger_accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_accounts_account", "(type = 'user_wallet') = (account_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_ledger_accounts_name", "(type = 'user_wallet') = (name IS NOT NULL)");

                            t.HasCheckConstraint("ck_ledger_accounts_name_blank", "name IS NULL OR btrim(name) <> ''");

                            t.HasCheckConstraint("ck_ledger_accounts_provider", "(type IN ('clearing','nostro','provider_expense')) = (provider IS NOT NULL)");

                            t.HasCheckConstraint("ck_ledger_accounts_provider_blank", "provider IS NULL OR btrim(provider) <> ''");

                            t.HasCheckConstraint("ck_ledger_accounts_type", "type IN ('user_wallet','clearing','revenue','nostro','provider_expense')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "TRY",
                            Type = "revenue"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "TRY",
                            Provider = "stripe-fake",
                            Type = "clearing"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "TRY",
                            Provider = "bank-fake",
                            Type = "clearing"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "TRY",
                            Provider = "bank-fake",
                            Type = "nostro"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "TRY",
                            Provider = "stripe-fake",
                            Type = "provider_expense"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "TRY",
                            Provider = "bank-fake",
                            Type = "provider_expense"
                        });
                });

            modelBuilder.Entity("HiWallet.WalletService.Domain.Ledger.LedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_ledger_entries");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_ledger_entries_tx");

                    b.HasIndex("LedgerAccountId", "Currency")
                        .HasDatabaseName("ix_ledger_entries_ledger_account_currency");

                    b.HasIndex("LedgerAccountId", "Id")
                        .HasDatabaseName("ix_ledger_entries_ledger_account");

                    b.ToTable("ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_ledger_entries_amount", "amount <> 0");
                        });
                });

            modelBuilder.Entity("HiWallet.WalletService.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("LedgerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_account_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ledger_transactions");

                    b.HasIndex("LedgerAccountId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_ledger_tx_idem");

                    b.ToTable("ledger_transactions", (string)null);
                });

            modelBuilder.Entity("HiWallet.WalletService.Infrastructure.Persistence.BusinessDailySummary", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("Currency")
                        .HasColumnType("char(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<decimal>("Commission")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("commission");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_count");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("volume");

                    b.HasKey("AccountId", "Day", "Currency")
                        .HasName("pk_business_daily_summaries");

                    b.HasIndex("Day")
                        .HasDatabaseName("ix_business_daily_summaries_day");

                    b.ToTable("business_daily_summaries", (string)null);
                });

            modelBuilder.Entity("HiWallet.WalletService.Infrastructure.Persistence.ProcessedEvent", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<Guid?>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Provider", "EventId")
                        .HasName("pk_processed_events");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("HiWallet.WalletService.Infrastructure.Persistence.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid?>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_transaction_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ReplyPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reply_payload");

                    b.Property<string>("ReplyRoutingKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reply_routing_key");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.HasKey("MessageId")
                        .HasName("pk_processed_messages");

                    b.HasIndex("SagaId")
                        .HasDatabaseName("ix_processed_messages_saga");

                    b.ToTable("processed_messages", (string)null);
                });

            modelBuilder.Entity("HiWallet.WalletService.Infrastructure.Persistence.ProviderFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("actual_amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("expected_amount");

                    b.Property<string>("FeeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fee_type");

                    b.Property<string>("InvoiceRef")
                        .HasColumnType("text")
                        .HasColumnName("invoice_ref");

                    b.Property<Guid?>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_tx_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderRef")
                        .HasColumnType("text")
                        .HasColumnName("provider_ref");

                    b.Property<string>("SettlementModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("settlement_model");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_provider_fees");

                    b.HasIndex("InvoiceRef")
                        .HasDatabaseName("ix_provider_fees_invoice");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_provider_fees_tx");

                    b.HasIndex("Provider", "OccurredAt")
                        .HasDatabaseName("ix_provider_fees_unbilled")
                        .HasFilter("invoice_ref IS NULL");

                    b.ToTable("provider_fees", null, t =>
                        {
                            t.HasCheckConstraint("ck_provider_fees_settlement_model", "settlement_model IN ('net','invoiced')");
                        });
                });

            modelBuilder.Entity("HiWallet.WalletService.Infrastructure.Persistence.ProviderInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("expected_amount");

                    b.Property<int>("FeeCount")
                        .HasColumnType("integer")
                        .HasColumnName("fee_count");

                    b.Property<string>("InvoiceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_ref");

                    b.Property<Guid?>("LedgerTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_tx_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_provider_invoices");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_provider_invoices_pending")
                        .HasFilter("status = 'pending_review'");

                    b.HasIndex("Provider", "InvoiceRef")
                        .IsUnique()
                        .HasDatabaseName("ux_provider_invoices_ref");

                    b.ToTable("provider_invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_provider_invoices_status", "status IN ('applied','pending_review')");
                        });
                });

            modelBuilder.Entity("HiWallet.WalletService.Domain.Balances.LedgerBalance", b =>
                {
                    b.HasOne("HiWallet.WalletService.Domain.Ledger.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LedgerAccountId", "Currency")
                        .HasPrincipalKey("Id", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_balances_ledger_account");
                });

            modelBuilder.Entity("HiWallet.WalletService.Domain.Ledger.LedgerAccount", b =>
                {
                    b.HasOne("HiWallet.WalletService.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ledger_accounts_account");
                });

            modelBuilder.Entity("HiWallet.WalletService.Domain.Ledger.LedgerEntry", b =>
                {
                    b.HasOne("HiWallet.WalletService.Domain.Ledger.LedgerTransaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_transaction");

                    b.HasOne("HiWallet.WalletService.Domain.Ledger.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LedgerAccountId", "Currency")
                        .HasPrincipalKey("Id", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_entries_ledger_account");
                });

            modelBuilder.Entity("HiWallet.WalletService.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.HasOne("HiWallet.WalletService.Domain.Ledger.LedgerAccount", null)
                        .WithMany()
                        .HasForeignKey("LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ledger_transactions_ledger_account");
                });

            modelBuilder.Entity("HiWallet.WalletService.Domain.Ledger.LedgerTransaction", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
